# Generated by Django 2.2 on 2021-04-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='date',
            new_name='pub_date',
        ),
    ]
